application: dfp-amp-testing-1185
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /html
  static_dir: html

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /css
  static_dir: css


- url: /amp_tests
  static_dir: amp_tests

- url: /guides
  static_dir: guides


- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest